/*TABLAS:FIDE_NOMBRE_TB
LLAVES PRIMARIAS:EMPLOYEES_ID_EMPLEADO_PK
LLAVES FORANEAS:EMPLOYEES_ID_EMPLEADO_FK
INDEXES:EMPLOYEES_ID_EMPLEADO_IDX
SP:EMPLOYEES_OBTENER_SALARIO_SP
FUNCIONES:EMPLOYEES_OBTENER_SALARIO_FN
SECUENCIAS:ID_EMPLOYEES_SEQ
VISTAS:FIDE_USUARIOS_ACTIVOS_V
VISTAS M:FIDE_USUARIOS_ACTIVOS_VM
TRIGGERS:FIDE_USUARIOS_ACTIVOS_TRG
PAQUETES:FIDE_PROYECTO_FINAL_PKG
PROFILE:FIDE_PROYECTO_FINAL_PROF*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE TABLE FIDE_ERRORES_TB(USUARIO VARCHAR2(100),ORIGEN VARCHAR2(50),FECHA DATE,VERROR VARCHAR2(1024));*/
--------------------------------------------------------------------------------------------------------------------------------------
  /*CREATE SEQUENCE ID_ESTADO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

  CREATE TABLE FIDE_ESTADOS_TB (	
    ID_ESTADO NUMBER, 
	DESCRIPCION VARCHAR2(30)NOT NULL,  
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT ESTADOS_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)USING INDEX (CREATE INDEX ESTADOS_ID_ESTADO_IDX ON FIDE_ESTADOS_TB (ID_ESTADO)),
    CONSTRAINT ESTADOS_ESTADO_UNQ UNIQUE(ESTADO)
   );
   
   CREATE OR REPLACE TRIGGER FIDE_ID_ESTADO_TRG
    BEFORE INSERT ON FIDE_ESTADOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ESTADO IS NULL THEN
            SELECT ID_ESTADO_SEQ.NEXTVAL
            INTO :NEW.ID_ESTADO
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------   
    /*CREATE SEQUENCE ID_SEDE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_SEDES_TB (	
    ID_SEDE NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL, 
    CIUDAD VARCHAR2(50)NOT NULL,
    DIRECCION VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT SEDES_ID_SEDE_PK PRIMARY KEY (ID_SEDE)USING INDEX (CREATE INDEX SEDES_ID_SEDE_IDX ON FIDE_SEDES_TB (ID_SEDE)),
    CONSTRAINT SEDES_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_SEDE_TRG
    BEFORE INSERT ON FIDE_SEDES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_SEDE IS NULL THEN
            SELECT ID_SEDE_SEQ.NEXTVAL
            INTO :NEW.ID_SEDE
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_PUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_PUESTOS_TB (	
    ID_PUESTO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL, 
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT PUESTOS_ID_PUESTO_PK PRIMARY KEY (ID_PUESTO)USING INDEX (CREATE INDEX PUESTOS_ID_PUESTO_IDX ON FIDE_PUESTOS_TB (ID_PUESTO)),
    CONSTRAINT PUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_PUESTO_TRG
    BEFORE INSERT ON FIDE_PUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_PUESTO IS NULL THEN
            SELECT ID_PUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_PUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_SERVICIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_SERVICIOS_TB (	
    ID_SERVICIO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL, 
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT SERVICIOS_ID_SERVICIO_PK PRIMARY KEY (ID_SERVICIO)USING INDEX (CREATE INDEX SERVICIOS_ID_SERVICIO_IDX ON FIDE_SERVICIOS_TB (ID_SERVICIO)),
    CONSTRAINT SERVICIOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_SERVICIO_TRG
    BEFORE INSERT ON FIDE_SERVICIOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_SERVICIO IS NULL THEN
            SELECT ID_SERVICIO_SEQ.NEXTVAL
            INTO :NEW.ID_SERVICIO
            FROM DUAL;
        END IF;
    END;*/
---------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_CATEGORIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_CATEGORIAS_TB (	
    ID_CATEGORIA NUMBER, 
	DESCRIPCION VARCHAR2(100)NOT NULL,
    IMAGEN VARCHAR2(1024)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT CATEGORIAS_ID_CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA)USING INDEX (CREATE INDEX CATEGORIAS_ID_CATEGORIA_IDX ON FIDE_CATEGORIAS_TB (ID_CATEGORIA)),
    CONSTRAINT CATEGORIAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_CATEGORIA_TRG
    BEFORE INSERT ON FIDE_CATEGORIAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CATEGORIA IS NULL THEN
            SELECT ID_CATEGORIA_SEQ.NEXTVAL
            INTO :NEW.ID_CATEGORIA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_TIPO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_TIPOS_TB (	
    ID_TIPO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT TIPOS_ID_TIPO_PK PRIMARY KEY (ID_TIPO)USING INDEX (CREATE INDEX TIPOS_ID_TIPO_IDX ON FIDE_TIPOS_TB (ID_TIPO)),
    CONSTRAINT TIPOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_TIPO_TRG
    BEFORE INSERT ON FIDE_TIPOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_TIPO IS NULL THEN
            SELECT ID_TIPO_SEQ.NEXTVAL
            INTO :NEW.ID_TIPO
            FROM DUAL;
        END IF;
    END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_EMPLEADO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_EMPLEADOS_TB (	
    ID_EMPLEADO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    APELLIDO VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
    CORREO VARCHAR2(100)NOT NULL,
    FECHA_CONTRATO DATE NOT NULL,
    SALARIO VARCHAR2(500) NULL,
	ESTADO NUMBER(1) NOT NULL,
    ID_PUESTO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    CONSTRAINT EMPLEADOS_ID_EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO)USING INDEX (CREATE INDEX EMPLEADOS_ID_EMPLEADO_IDX ON FIDE_EMPLEADOS_TB (ID_EMPLEADO)),
    CONSTRAINT EMPLEADOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT EMPLEADOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT EMPLEADOS_ID_PUESTO_FK FOREIGN KEY (ID_PUESTO)REFERENCES FIDE_PUESTOS_TB (ID_PUESTO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_EMPLEADO_TRG
    BEFORE INSERT ON FIDE_EMPLEADOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_EMPLEADO IS NULL THEN
            SELECT ID_EMPLEADO_SEQ.NEXTVAL
            INTO :NEW.ID_EMPLEADO
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE TABLE FIDE_USUARIOS_TB (	
    ID_USUARIO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    APELLIDO VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
    CORREO VARCHAR2(100)NOT NULL,
    USERNAME VARCHAR2(50)NOT NULL,
    UPASSWORD VARCHAR2(500)NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT USUARIOS_ID_USUARIO_PK PRIMARY KEY(ID_USUARIO)USING INDEX (CREATE INDEX USUARIOS_ID_USUARIO_IDX ON FIDE_USUARIOS_TB (ID_USUARIO)),
    CONSTRAINT USUARIOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT USUARIOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));*/
----------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_ROL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_ROLES_TB (	
    ID_ROL NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY (ID_ROL)USING INDEX (CREATE INDEX ROLES_ID_ROL_IDX ON FIDE_ROLES_TB (ID_ROL)),
    CONSTRAINT ROLES_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO)REFERENCES FIDE_USUARIOS_TB (ID_USUARIO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_ROL_TRG
    BEFORE INSERT ON FIDE_ROLES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ROL IS NULL THEN
            SELECT ID_ROL_SEQ.NEXTVAL
            INTO :NEW.ID_ROL
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MARCA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MARCAS_TB (	
    ID_MARCA NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MARCAS_ID_MARCA_PK PRIMARY KEY (ID_MARCA)USING INDEX (CREATE INDEX MARCAS_ID_MARCA_IDX ON FIDE_MARCAS_TB (ID_MARCA)),
    CONSTRAINT MARCAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MARCA_TRG
    BEFORE INSERT ON FIDE_MARCAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MARCA IS NULL THEN
            SELECT ID_MARCA_SEQ.NEXTVAL
            INTO :NEW.ID_MARCA
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MODELO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MODELOS_TB (	
    ID_MODELO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MODELOS_ID_MODELO_PK PRIMARY KEY (ID_MODELO)USING INDEX (CREATE INDEX MODELOS_ID_MODELO_IDX ON FIDE_MODELOS_TB (ID_MODELO)),
    CONSTRAINT MODELOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT MODELOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MODELO_TRG
    BEFORE INSERT ON FIDE_MODELOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MODELO IS NULL THEN
            SELECT ID_MODELO_SEQ.NEXTVAL
            INTO :NEW.ID_MODELO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE TABLE FIDE_VEHICULOS_TB (	
    PLACA VARCHAR2(30), 
	ID_MARCA NUMBER NOT NULL,
    ID_MODELO NUMBER NOT NULL,
    ID_TIPO NUMBER NOT NULL,
    AÑO NUMBER(4) NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT VEHICULOS_PLACA_PK PRIMARY KEY(PLACA)USING INDEX (CREATE INDEX VEHICULOS_PLACA_IDX ON FIDE_VEHICULOS_TB (PLACA)),
    CONSTRAINT VEHICULOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT VEHICULOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT VEHICULOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT VEHICULOS_ID_MODELO_FK FOREIGN KEY (ID_MODELO)REFERENCES FIDE_MODELOS_TB (ID_MODELO),
    CONSTRAINT VEHICULOS_ID_TIPO_FK FOREIGN KEY (ID_TIPO)REFERENCES FIDE_TIPOS_TB (ID_TIPO),
    CONSTRAINT VEHICULOS_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO)REFERENCES FIDE_USUARIOS_TB (ID_USUARIO));*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_CITA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_CITAS_TB (	
    ID_CITA NUMBER, 
	PLACA VARCHAR2(30)NOT NULL,
    FECHA DATE NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT CITAS_ID_CITA_PK PRIMARY KEY (ID_CITA)USING INDEX (CREATE INDEX CITAS_ID_CITA_IDX ON FIDE_CITAS_TB (ID_CITA)),
    CONSTRAINT CITAS_PLACA_FK FOREIGN KEY (PLACA)REFERENCES FIDE_VEHICULOS_TB (PLACA),
    CONSTRAINT CITAS_ID_SERVICIO_FK FOREIGN KEY (ID_SERVICIO)REFERENCES FIDE_SERVICIOS_TB (ID_SERVICIO),
    CONSTRAINT CITAS_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES FIDE_EMPLEADOS_TB (ID_EMPLEADO),
    CONSTRAINT CITAS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT CITAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_CITA_TRG
    BEFORE INSERT ON FIDE_CITAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CITA IS NULL THEN
            SELECT ID_CITA_SEQ.NEXTVAL
            INTO :NEW.ID_CITA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_REPUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_REPUESTOS_TB (	
    ID_REPUESTO NUMBER, 
	IMAGEN VARCHAR2(1024) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT REPUESTOS_ID_REPUESTO_PK PRIMARY KEY (ID_REPUESTO)USING INDEX (CREATE INDEX REPUESTOS_ID_REPUESTO_IDX ON FIDE_REPUESTOS_TB (ID_REPUESTO)),
    CONSTRAINT REPUESTOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT REPUESTOS_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA)REFERENCES FIDE_CATEGORIAS_TB (ID_CATEGORIA),
    CONSTRAINT REPUESTOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT REPUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_REPUESTO_TRG
    BEFORE INSERT ON FIDE_REPUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_REPUESTO IS NULL THEN
            SELECT ID_REPUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_REPUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_ORDEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_ORDENES_TB (	
    ID_ORDEN NUMBER, 
	ID_CITA NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    COMENTARIOS VARCHAR2(1500) NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    CONSTRAINT ORDENES_ID_ORDEN_PK PRIMARY KEY (ID_ORDEN)USING INDEX (CREATE INDEX ORDENES_ID_ORDEN_IDX ON FIDE_ORDENES_TB (ID_ORDEN)),
    CONSTRAINT ORDENES_ID_CITA_FK FOREIGN KEY (ID_CITA)REFERENCES FIDE_CITAS_TB (ID_CITA),
    CONSTRAINT ORDENES_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES FIDE_EMPLEADOS_TB (ID_EMPLEADO),
    CONSTRAINT ORDENES_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_ORDEN_TRG
    BEFORE INSERT ON FIDE_ORDENES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ORDEN IS NULL THEN
            SELECT ID_ORDEN_SEQ.NEXTVAL
            INTO :NEW.ID_ORDEN
            FROM DUAL;
        END IF;
    END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_FACTURA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_FACTURAS_TB (	
    ID_FACTURA NUMBER, 
	ID_SEDE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    PRECIO_FINAL NUMBER NOT NULL,
    CONSTRAINT FACTURAS_ID_FACTURA_PK PRIMARY KEY (ID_FACTURA)USING INDEX (CREATE INDEX FACTURAS_ID_FACTURA_IDX ON FIDE_FACTURAS_TB (ID_FACTURA)),
    CONSTRAINT FACTURAS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_FACTURA_TRG
    BEFORE INSERT ON FIDE_FACTURAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_FACTURA IS NULL THEN
            SELECT ID_FACTURA_SEQ.NEXTVAL
            INTO :NEW.ID_FACTURA
            FROM DUAL;
        END IF;
    END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_DETALLE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_DETALLES_TB (	
    ID_DETALLE NUMBER, 
	ID_FACTURA NUMBER NOT NULL,
    ID_ORDEN NUMBER NOT NULL,
    ID_REPUESTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER NOT NULL,
    CONSTRAINT DETALLES_ID_DETALLE_PK PRIMARY KEY (ID_DETALLE)USING INDEX (CREATE INDEX DETALLES_ID_DETALLE_IDX ON FIDE_DETALLES_TB (ID_DETALLE)),
    CONSTRAINT DETALLES_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA)REFERENCES FIDE_FACTURAS_TB (ID_FACTURA),
    CONSTRAINT DETALLES_ID_ORDEN_FK FOREIGN KEY (ID_ORDEN)REFERENCES FIDE_ORDENES_TB (ID_ORDEN),
    CONSTRAINT DETALLES_ID_REPUESTO_FK FOREIGN KEY (ID_REPUESTO)REFERENCES FIDE_REPUESTOS_TB (ID_REPUESTO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_DETALLE_TRG
    BEFORE INSERT ON FIDE_DETALLES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_DETALLE IS NULL THEN
            SELECT ID_DETALLE_SEQ.NEXTVAL
            INTO :NEW.ID_DETALLE
            FROM DUAL;
        END IF;
    END;*/   
---------------------------------------------------------------------------------------------------------------------------------------------------------------------    
INSERT INTO FIDE_ESTADOS_TB (DESCRIPCION, ESTADO) VALUES ('Activo', 1);
INSERT INTO FIDE_ESTADOS_TB (DESCRIPCION, ESTADO) VALUES ('Inactivo', 0);
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller TF', 'San Jose', 'Bajo Piuses', '89984395', 1);

INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller Los Amigos', 'Heredia', 'El Carao', '72063542', 1);

INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller Sebas', 'Alajuela', 'San Rafael', '88888888', 1);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_USUARIOS_TB (ID_USUARIO,NOMBRE, APELLIDO, TELEFONO, CORREO, USERNAME, UPASSWORD, ID_SEDE, ESTADO)
VALUES (115470088,'Hector', 'Hernandez', '72063542', 'hhernan93vargas@gmail.com', 'hhernan', '$2a$12$pmBd.ZI04Cw/Oa1SKRXX1ead2W1sVn/1avq6GBjc76Tfaf1PYW4re', 1, 1);
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_ROLES_TB (NOMBRE, ID_USUARIO)
VALUES ('ROLE_ADMIN', 115470088);
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE ADD_JUEGO (IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER ) AS 
BEGIN
    INSERT INTO JUEGO (IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA) VALUES (IMG,NOM,EMP,PREC,EXI,EST,ID_CAT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE DELETE_JUEGO (JID IN NUMBER ) AS
BEGIN
    DELETE FROM JUEGO WHERE ID_JUEGO=JID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;*/
----------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE GET_JUEGOS (DATOS OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE GET_JUEGOSBYCATEGORIA (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE GET_CATEGORIAS (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA, DESCRIPCION FROM CATEGORIA;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE GET_CATEGORIA_DESC (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION FROM CATEGORIA;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE UPDATE_JUEGO (JID IN NUMBER,IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER ) AS
BEGIN
    UPDATE JUEGO SET IMAGEN = IMG ,NOMBRE = NOM,EMPRESA = EMP,PRECIO = PREC ,EXISTENCIAS = EXI ,ESTADO = EST,ID_CATEGORIA=ID_CAT  WHERE ID_JUEGO=JID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
create or replace PROCEDURE GET_ONE_JUEGO (JID IN NUMBER,DATOS OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO WHERE ID_JUEGO=JID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE ADD_FACTURA (USID IN NUMBER,FECHA IN DATE,TOTAL IN NUMBER) AS

BEGIN
    INSERT INTO FACTURA (ID_USUARIO,FECHA,TOTAL) VALUES (USID,FECHA,TOTAL);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE GET_FACTURA_ID (FECH IN DATE,DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_FACTURA FROM FACTURA WHERE FECHA=FECH;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE UPDATE_FACTURA (FID IN NUMBER,TOTL IN NUMBER) AS

BEGIN
    UPDATE FACTURA SET TOTAL=TOTL WHERE ID_FACTURA=FID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE ADD_DETALLE_FACTURA (IDFACT IN NUMBER,IDJUEGO IN NUMBER,PRECIO IN NUMBER,CANTIDAD IN NUMBER ) AS
BEGIN
    INSERT INTO DETALLE_FACTURA (ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) VALUES (IDFACT,IDJUEGO,PRECIO,CANTIDAD);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------





----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_ROLES_TB_ADD_ROL_SP (RNAME IN VARCHAR2,IDUSER IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_ROLES_TB (NOMBRE,ID_USUARIO) VALUES (RNAME,IDUSER);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_ADD_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_ROLES_TB_DELETE_ROL_SP (IDU IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_ROLES_TB WHERE ID_USUARIO=IDU;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_DELETE_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_DELETE_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_TB_ADD_USUARIO_SP (USID IN NUMBER,UNAME IN VARCHAR2,PASS IN VARCHAR2,UNOM IN VARCHAR2,APELL IN VARCHAR2,CORRE IN VARCHAR2,TEL IN VARCHAR2,IDS IN NUMBER,EST IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    INSERT INTO FIDE_USUARIOS_TB (ID_USUARIO,USERNAME, UPASSWORD,NOMBRE, APELLIDO,CORREO,TELEFONO,ID_SEDE,ESTADO) VALUES (USID,UNAME,PASS,UNOM, APELL,CORRE,TEL,IDS,EST);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_ADD_USUARIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_TB_DELETE_USUARIO_SP (USEID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    FIDE_ROLES_TB_DELETE_ROL_SP(USEID);
    DELETE FROM FIDE_USUARIOS_TB WHERE ID_USUARIO=USEID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_DELETE_USUARIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_TB_UPDATE_USUARIO_SP (USERID IN NUMBER,USNAM IN VARCHAR2,CONTRAS IN VARCHAR2,NOMBR IN VARCHAR2,APELLI IN VARCHAR2,MAIL IN VARCHAR2,PHONE IN VARCHAR2,IDS IN NUMBER,ACTV IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    UPDATE FIDE_USUARIOS_TB SET USERNAME=USNAM, UPASSWORD=CONTRAS,NOMBRE=NOMBR, APELLIDO=APELLI,CORREO=MAIL, TELEFONO=PHONE,ID_SEDE=IDS,ESTADO=ACTV WHERE ID_USUARIO=USERID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_UPDATE_USUARIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE,ESTADO FROM FIDE_USUARIOS_TB;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOBYID_SP (UID IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE ID_USUARIO = UID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOBYUSERNAME_SP (UNAME IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE USERNAME = UNAME;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYUSERNAME_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYUSERNAME_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USERNAMEANDPASSWORD_SP(UNAME IN VARCHAR2, PASS IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE USERNAME = UNAME and UPASSWORD = PASS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEANDPASSWORD_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEANDPASSWORD_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USERNAMEORCORREO_SP(UNAME IN VARCHAR2, CORRE IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE USERNAME = UNAME OR CORREO = CORRE;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEORCORREO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEORCORREO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE FUNCTION FIDE_USUARIOS_TB_USUARIO_EXISTE_FN (UNAME IN VARCHAR2, CORRE IN VARCHAR2) RETURN NUMBER
IS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    FOR DATOS IN (SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB) LOOP
        IF DATOS.USERNAME = UNAME OR DATOS.CORREO = CORRE THEN
            RETURN 1; -- TRUE
        END IF;
    END LOOP;
    RETURN 0; -- FALSE
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );
        RETURN -1;

    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );
        RETURN -1;
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_ROLES_SP(UID IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT NOMBRE FROM FIDE_ROLES_TB
   WHERE ID_USUARIO = UID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );

    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_SEDES_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB
   WHERE ESTADO=1;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_SEDES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SEDES_TB_GET_SEDES_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_SEDES_TB_GET_SEDESBYID_SP (IDS IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB
   WHERE ID_SEDE = IDS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDESBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDESBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_SEDES_TB_ADD_SEDE_SP (NOMB IN VARCHAR2,CIT IN VARCHAR2,DIR IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_SEDES_TB (NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO) VALUES (NOMB,CIT,DIR,TEL,EST);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_ADD_SEDE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_SEDES_TB_DELETE_SEDE_SP (IDS IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_SEDES_TB WHERE ID_SEDE=IDS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_DELETE_SEDE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SEDES_TB_UPDATE_SEDE_SP (IDS IN NUMBER,NOMB IN VARCHAR2,CIT IN VARCHAR2,DIR IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_SEDES_TB SET NOMBRE=NOMB,CIUDAD=CIT,DIRECCION=DIR,TELEFONO=TEL,ESTADO=EST WHERE ID_SEDE=IDS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_UPDATE_SEDE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CATEGORIAS_TB_GET_CATEGORIA_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,IMAGEN,ESTADO FROM FIDE_CATEGORIAS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CATEGORIAS_TB_GET_ONE_CATEGORIA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,IMAGEN,ESTADO FROM FIDE_CATEGORIAS_TB WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_ONE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_ONE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------- 
/*CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_TB_ADD_CATEGORIA_SP (DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_CATEGORIAS_TB (DESCRIPCION,IMAGEN,ESTADO) VALUES (DESCRIP,IMG,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_ADD_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_TB_DELETE_CATEGORIA_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_CATEGORIAS_TB WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_DELETE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_TB_UPDATE_CATEGORIA_SP (CID IN NUMBER,DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_CATEGORIAS_TB SET DESCRIPCION = DESCRIP ,IMAGEN = IMG,ESTADO = ACT WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_UPDATE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SERVICIOS_TB_GET_SERVICIOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SERVICIO,NOMBRE,ESTADO FROM FIDE_SERVICIOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SERVICIOS_TB_GET_SERVICIO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SERVICIO,NOMBRE,ESTADO FROM FIDE_SERVICIOS_TB WHERE ID_SERVICIO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_TB_ADD_SERVICIO_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_SERVICIOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_ADD_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_TB_DELETE_SERVICIO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_SERVICIOS_TB WHERE ID_SERVICIO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_DELETE_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_TB_UPDATE_SERVICIO_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_SERVICIOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_SERVICIO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_UPDATE_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_TIPOS_TB_GET_TIPOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_TIPO,NOMBRE,ESTADO FROM FIDE_TIPOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_TIPOS_TB_GET_TIPO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_TIPO,NOMBRE,ESTADO FROM FIDE_TIPOS_TB WHERE ID_TIPO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_TIPOS_TB_ADD_TIPO_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_TIPOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_ADD_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_TIPOS_TB_DELETE_TIPO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_TIPOS_TB WHERE ID_TIPO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_DELETE_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_TIPOS_TB_UPDATE_TIPO_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_TIPOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_TIPO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_UPDATE_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_PUESTOS_TB_GET_PUESTOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_PUESTO,NOMBRE,ESTADO FROM FIDE_PUESTOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_PUESTOS_TB_GET_PUESTO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_PUESTO,NOMBRE,ESTADO FROM FIDE_PUESTOS_TB WHERE ID_PUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_PUESTOS_TB_ADD_PUESTO_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_PUESTOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_ADD_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_PUESTOS_TB_DELETE_PUESTO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_PUESTOS_TB WHERE ID_PUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_DELETE_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_PUESTOS_TB_UPDATE_PUESTO_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_PUESTOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_PUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_UPDATE_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_TB_GET_MARCAS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA,NOMBRE,ESTADO FROM FIDE_MARCAS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCAS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_TB_GET_MARCA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA,NOMBRE,ESTADO FROM FIDE_MARCAS_TB WHERE ID_MARCA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_TB_ADD_MARCA_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_MARCAS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_ADD_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_TB_DELETE_MARCA_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_MARCAS_TB WHERE ID_MARCA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_DELETE_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_TB_UPDATE_MARCA_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_MARCAS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_MARCA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_UPDATE_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MODELOS_TB_GET_MODELOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MODELO,NOMBRE,ID_MARCA,ESTADO FROM FIDE_MODELOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MODELOS_TB_GET_MODELO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MODELO,NOMBRE,ID_MARCA,ESTADO FROM FIDE_MODELOS_TB WHERE ID_MODELO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MODELOS_TB_ADD_MODELO_SP (NOM IN VARCHAR2,MID IN NUMBER,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_MODELOS_TB (NOMBRE,ID_MARCA,ESTADO) VALUES (NOM,MID,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_ADD_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MODELOS_TB_DELETE_MODELO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_MODELOS_TB WHERE ID_MODELO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_DELETE_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MODELOS_TB_UPDATE_MODELO_SP (CID IN NUMBER,NOM IN VARCHAR2,MID IN NUMBER, ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_MODELOS_TB SET NOMBRE=NOM,ID_MARCA=MID,ESTADO=ACT WHERE ID_MODELO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_UPDATE_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MODELOS_TB_GET_MARCAS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA,NOMBRE,ESTADO FROM FIDE_MARCAS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MARCAS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




















    
    