/*TABLAS:FIDE_NOMBRE_TB
LLAVES PRIMARIAS:EMPLOYEES_ID_EMPLEADO_PK
LLAVES FORANEAS:EMPLOYEES_ID_EMPLEADO_FK
INDEXES:EMPLOYEES_ID_EMPLEADO_IDX
SP:EMPLOYEES_OBTENER_SALARIO_SP
FUNCIONES:EMPLOYEES_OBTENER_SALARIO_FN
SECUENCIAS:ID_EMPLOYEES_SEQ
VISTAS:FIDE_USUARIOS_ACTIVOS_V
VISTAS M:FIDE_USUARIOS_ACTIVOS_VM
TRIGGERS:FIDE_USUARIOS_ACTIVOS_TRG
PAQUETES:FIDE_PROYECTO_FINAL_PKG
PROFILE:FIDE_PROYECTO_FINAL_PROF*/
--------------------------------------------------------------------------------------------------------------------------------------
  /*CREATE SEQUENCE ID_ESTADO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

  CREATE TABLE FIDE_ESTADOS_TB (	
    ID_ESTADO NUMBER, 
	DESCRIPCION VARCHAR2(30)NOT NULL,  
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT ESTADOS_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)USING INDEX (CREATE INDEX ESTADOS_ID_ESTADO_IDX ON FIDE_ESTADOS_TB (ID_ESTADO)),
    CONSTRAINT ESTADOS_ESTADO_UNQ UNIQUE(ESTADO)
   );
   
   CREATE OR REPLACE TRIGGER FIDE_ID_ESTADO_TRG
    BEFORE INSERT ON FIDE_ESTADOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ESTADO IS NULL THEN
            SELECT ID_ESTADO_SEQ.NEXTVAL
            INTO :NEW.ID_ESTADO
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------   
    /*CREATE SEQUENCE ID_SEDE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_SEDES_TB (	
    ID_SEDE NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL, 
    CIUDAD VARCHAR2(50)NOT NULL,
    DIRECCION VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT SEDES_ID_SEDE_PK PRIMARY KEY (ID_SEDE)USING INDEX (CREATE INDEX SEDES_ID_SEDE_IDX ON FIDE_SEDES_TB (ID_SEDE)),
    CONSTRAINT SEDES_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_SEDE_TRG
    BEFORE INSERT ON FIDE_SEDES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_SEDE IS NULL THEN
            SELECT ID_SEDE_SEQ.NEXTVAL
            INTO :NEW.ID_SEDE
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_PUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_PUESTOS_TB (	
    ID_PUESTO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL, 
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT PUESTOS_ID_PUESTO_PK PRIMARY KEY (ID_PUESTO)USING INDEX (CREATE INDEX PUESTOS_ID_PUESTO_IDX ON FIDE_PUESTOS_TB (ID_PUESTO)),
    CONSTRAINT PUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_PUESTO_TRG
    BEFORE INSERT ON FIDE_PUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_PUESTO IS NULL THEN
            SELECT ID_PUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_PUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_SERVICIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_SERVICIOS_TB (	
    ID_SERVICIO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL, 
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT SERVICIOS_ID_SERVICIO_PK PRIMARY KEY (ID_SERVICIO)USING INDEX (CREATE INDEX SERVICIOS_ID_SERVICIO_IDX ON FIDE_SERVICIOS_TB (ID_SERVICIO)),
    CONSTRAINT SERVICIOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_SERVICIO_TRG
    BEFORE INSERT ON FIDE_SERVICIOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_SERVICIO IS NULL THEN
            SELECT ID_SERVICIO_SEQ.NEXTVAL
            INTO :NEW.ID_SERVICIO
            FROM DUAL;
        END IF;
    END;*/
---------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_CATEGORIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_CATEGORIAS_TB (	
    ID_CATEGORIA NUMBER, 
	DESCRIPCION VARCHAR2(100)NOT NULL,
    IMAGEN VARCHAR2(1024)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT CATEGORIAS_ID_CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA)USING INDEX (CREATE INDEX CATEGORIAS_ID_CATEGORIA_IDX ON FIDE_CATEGORIAS_TB (ID_CATEGORIA)),
    CONSTRAINT CATEGORIAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_CATEGORIA_TRG
    BEFORE INSERT ON FIDE_CATEGORIAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CATEGORIA IS NULL THEN
            SELECT ID_CATEGORIA_SEQ.NEXTVAL
            INTO :NEW.ID_CATEGORIA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_TIPO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_TIPOS_TB (	
    ID_TIPO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT TIPOS_ID_TIPO_PK PRIMARY KEY (ID_TIPO)USING INDEX (CREATE INDEX TIPOS_ID_TIPO_IDX ON FIDE_TIPOS_TB (ID_TIPO)),
    CONSTRAINT TIPOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_TIPO_TRG
    BEFORE INSERT ON FIDE_TIPOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_TIPO IS NULL THEN
            SELECT ID_TIPO_SEQ.NEXTVAL
            INTO :NEW.ID_TIPO
            FROM DUAL;
        END IF;
    END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_EMPLEADO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_EMPLEADOS_TB (	
    ID_EMPLEADO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    APELLIDO VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
    CORREO VARCHAR2(100)NOT NULL,
    FECHA_CONTRATO DATE NOT NULL,
    SALARIO VARCHAR2(500) NULL,
	ESTADO NUMBER(1) NOT NULL,
    ID_PUESTO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    CONSTRAINT EMPLEADOS_ID_EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO)USING INDEX (CREATE INDEX EMPLEADOS_ID_EMPLEADO_IDX ON FIDE_EMPLEADOS_TB (ID_EMPLEADO)),
    CONSTRAINT EMPLEADOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT EMPLEADOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT EMPLEADOS_ID_PUESTO_FK FOREIGN KEY (ID_PUESTO)REFERENCES FIDE_PUESTOS_TB (ID_PUESTO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_EMPLEADO_TRG
    BEFORE INSERT ON FIDE_EMPLEADOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_EMPLEADO IS NULL THEN
            SELECT ID_EMPLEADO_SEQ.NEXTVAL
            INTO :NEW.ID_EMPLEADO
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE TABLE FIDE_USUARIOS_TB (	
    ID_USUARIO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    APELLIDO VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
    CORREO VARCHAR2(100)NOT NULL,
    USERNAME VARCHAR2(50)NOT NULL,
    UPASSWORD VARCHAR2(500)NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT USUARIOS_ID_USUARIO_PK PRIMARY KEY(ID_USUARIO)USING INDEX (CREATE INDEX USUARIOS_ID_USUARIO_IDX ON FIDE_USUARIOS_TB (ID_USUARIO)),
    CONSTRAINT USUARIOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT USUARIOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));*/
----------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_ROL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_ROLES_TB (	
    ID_ROL NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY (ID_ROL)USING INDEX (CREATE INDEX ROLES_ID_ROL_IDX ON FIDE_ROLES_TB (ID_ROL)),
    CONSTRAINT ROLES_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO)REFERENCES FIDE_USUARIOS_TB (ID_USUARIO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_ROL_TRG
    BEFORE INSERT ON FIDE_ROLES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ROL IS NULL THEN
            SELECT ID_ROL_SEQ.NEXTVAL
            INTO :NEW.ID_ROL
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MARCA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MARCAS_TB (	
    ID_MARCA NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MARCAS_ID_MARCA_PK PRIMARY KEY (ID_MARCA)USING INDEX (CREATE INDEX MARCAS_ID_MARCA_IDX ON FIDE_MARCAS_TB (ID_MARCA)),
    CONSTRAINT MARCAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MARCA_TRG
    BEFORE INSERT ON FIDE_MARCAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MARCA IS NULL THEN
            SELECT ID_MARCA_SEQ.NEXTVAL
            INTO :NEW.ID_MARCA
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MODELO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MODELOS_TB (	
    ID_MODELO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MODELOS_ID_MODELO_PK PRIMARY KEY (ID_MODELO)USING INDEX (CREATE INDEX MODELOS_ID_MODELO_IDX ON FIDE_MODELOS_TB (ID_MODELO)),
    CONSTRAINT MODELOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT MODELOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MODELO_TRG
    BEFORE INSERT ON FIDE_MODELOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MODELO IS NULL THEN
            SELECT ID_MODELO_SEQ.NEXTVAL
            INTO :NEW.ID_MODELO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE TABLE FIDE_VEHICULOS_TB (	
    PLACA VARCHAR2(30), 
	ID_MARCA NUMBER NOT NULL,
    ID_MODELO NUMBER NOT NULL,
    ID_TIPO NUMBER NOT NULL,
    AÑO NUMBER(4) NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT VEHICULOS_PLACA_PK PRIMARY KEY(PLACA)USING INDEX (CREATE INDEX VEHICULOS_PLACA_IDX ON FIDE_VEHICULOS_TB (PLACA)),
    CONSTRAINT VEHICULOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT VEHICULOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT VEHICULOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT VEHICULOS_ID_MODELO_FK FOREIGN KEY (ID_MODELO)REFERENCES FIDE_MODELOS_TB (ID_MODELO),
    CONSTRAINT VEHICULOS_ID_TIPO_FK FOREIGN KEY (ID_TIPO)REFERENCES FIDE_TIPOS_TB (ID_TIPO),
    CONSTRAINT VEHICULOS_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO)REFERENCES FIDE_USUARIOS_TB (ID_USUARIO));*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_CITA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_CITAS_TB (	
    ID_CITA NUMBER, 
	PLACA VARCHAR2(30)NOT NULL,
    FECHA DATE NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT CITAS_ID_CITA_PK PRIMARY KEY (ID_CITA)USING INDEX (CREATE INDEX CITAS_ID_CITA_IDX ON FIDE_CITAS_TB (ID_CITA)),
    CONSTRAINT CITAS_PLACA_FK FOREIGN KEY (PLACA)REFERENCES FIDE_VEHICULOS_TB (PLACA),
    CONSTRAINT CITAS_ID_SERVICIO_FK FOREIGN KEY (ID_SERVICIO)REFERENCES FIDE_SERVICIOS_TB (ID_SERVICIO),
    CONSTRAINT CITAS_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES FIDE_EMPLEADOS_TB (ID_EMPLEADO),
    CONSTRAINT CITAS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT CITAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_CITA_TRG
    BEFORE INSERT ON FIDE_CITAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CITA IS NULL THEN
            SELECT ID_CITA_SEQ.NEXTVAL
            INTO :NEW.ID_CITA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_REPUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_REPUESTOS_TB (	
    ID_REPUESTO NUMBER, 
	IMAGEN VARCHAR2(1024) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT REPUESTOS_ID_REPUESTO_PK PRIMARY KEY (ID_REPUESTO)USING INDEX (CREATE INDEX REPUESTOS_ID_REPUESTO_IDX ON FIDE_REPUESTOS_TB (ID_REPUESTO)),
    CONSTRAINT REPUESTOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT REPUESTOS_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA)REFERENCES FIDE_CATEGORIAS_TB (ID_CATEGORIA),
    CONSTRAINT REPUESTOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT REPUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_REPUESTO_TRG
    BEFORE INSERT ON FIDE_REPUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_REPUESTO IS NULL THEN
            SELECT ID_REPUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_REPUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_ORDEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_ORDENES_TB (	
    ID_ORDEN NUMBER, 
	ID_CITA NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    COMENTARIOS VARCHAR2(1500) NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    CONSTRAINT ORDENES_ID_ORDEN_PK PRIMARY KEY (ID_ORDEN)USING INDEX (CREATE INDEX ORDENES_ID_ORDEN_IDX ON FIDE_ORDENES_TB (ID_ORDEN)),
    CONSTRAINT ORDENES_ID_CITA_FK FOREIGN KEY (ID_CITA)REFERENCES FIDE_CITAS_TB (ID_CITA),
    CONSTRAINT ORDENES_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES FIDE_EMPLEADOS_TB (ID_EMPLEADO),
    CONSTRAINT ORDENES_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_ORDEN_TRG
    BEFORE INSERT ON FIDE_ORDENES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ORDEN IS NULL THEN
            SELECT ID_ORDEN_SEQ.NEXTVAL
            INTO :NEW.ID_ORDEN
            FROM DUAL;
        END IF;
    END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_FACTURA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_FACTURAS_TB (	
    ID_FACTURA NUMBER, 
	ID_SEDE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    PRECIO_FINAL NUMBER NOT NULL,
    CONSTRAINT FACTURAS_ID_FACTURA_PK PRIMARY KEY (ID_FACTURA)USING INDEX (CREATE INDEX FACTURAS_ID_FACTURA_IDX ON FIDE_FACTURAS_TB (ID_FACTURA)),
    CONSTRAINT FACTURAS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_FACTURA_TRG
    BEFORE INSERT ON FIDE_FACTURAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_FACTURA IS NULL THEN
            SELECT ID_FACTURA_SEQ.NEXTVAL
            INTO :NEW.ID_FACTURA
            FROM DUAL;
        END IF;
    END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_DETALLE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_DETALLES_TB (	
    ID_DETALLE NUMBER, 
	ID_FACTURA NUMBER NOT NULL,
    ID_ORDEN NUMBER NOT NULL,
    ID_REPUESTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER NOT NULL,
    CONSTRAINT DETALLES_ID_DETALLE_PK PRIMARY KEY (ID_DETALLE)USING INDEX (CREATE INDEX DETALLES_ID_DETALLE_IDX ON FIDE_DETALLES_TB (ID_DETALLE)),
    CONSTRAINT DETALLES_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA)REFERENCES FIDE_FACTURAS_TB (ID_FACTURA),
    CONSTRAINT DETALLES_ID_ORDEN_FK FOREIGN KEY (ID_ORDEN)REFERENCES FIDE_ORDENES_TB (ID_ORDEN),
    CONSTRAINT DETALLES_ID_REPUESTO_FK FOREIGN KEY (ID_REPUESTO)REFERENCES FIDE_REPUESTOS_TB (ID_REPUESTO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_DETALLE_TRG
    BEFORE INSERT ON FIDE_DETALLES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_DETALLE IS NULL THEN
            SELECT ID_DETALLE_SEQ.NEXTVAL
            INTO :NEW.ID_DETALLE
            FROM DUAL;
        END IF;
    END;*/   
---------------------------------------------------------------------------------------------------------------------------------------------------------------------    
INSERT INTO FIDE_ESTADOS_TB (DESCRIPCION, ESTADO) VALUES ('Activo', 1);
INSERT INTO FIDE_ESTADOS_TB (DESCRIPCION, ESTADO) VALUES ('Inactivo', 0);
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller TF', 'San Jose', 'Bajo Piuses', '89984395', 1);

INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller Los Amigos', 'Heredia', 'El Carao', '72063542', 1);

INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller Sebas', 'Alajuela', 'San Rafael', '88888888', 1);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_USUARIOS_TB (ID_USUARIO,NOMBRE, APELLIDO, TELEFONO, CORREO, USERNAME, UPASSWORD, ID_SEDE, ESTADO)
VALUES (115470088,'Hector', 'Hernandez', '72063542', 'hhernan93vargas@gmail.com', 'hhernan', '$2a$12$pmBd.ZI04Cw/Oa1SKRXX1ead2W1sVn/1avq6GBjc76Tfaf1PYW4re', 1, 1);
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_ROLES_TB (NOMBRE, ID_USUARIO)
VALUES ('ROLE_ADMIN', 115470088);
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




















    
    