/*TABLAS:FIDE_NOMBRE_TB
LLAVES PRIMARIAS:EMPLOYEES_ID_EMPLEADO_PK
LLAVES FORANEAS:EMPLOYEES_ID_EMPLEADO_FK
INDEXES:EMPLOYEES_ID_EMPLEADO_IDX
SP:EMPLOYEES_OBTENER_SALARIO_SP
FUNCIONES:EMPLOYEES_OBTENER_SALARIO_FN
SECUENCIAS:ID_EMPLOYEES_SEQ
VISTAS:FIDE_USUARIOS_ACTIVOS_V
VISTAS M:FIDE_USUARIOS_ACTIVOS_VM
TRIGGERS:FIDE_USUARIOS_ACTIVOS_TRG
PAQUETES:FIDE_PROYECTO_FINAL_PKG
PROFILE:FIDE_PROYECTO_FINAL_PROF*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE TABLE FIDE_ERRORES_TB(USUARIO VARCHAR2(100),ORIGEN VARCHAR2(50),FECHA DATE,VERROR VARCHAR2(1024));*/
--------------------------------------------------------------------------------------------------------------------------------------
  /*CREATE SEQUENCE ID_ESTADO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

  CREATE TABLE FIDE_ESTADOS_TB (	
    ID_ESTADO NUMBER, 
	DESCRIPCION VARCHAR2(30)NOT NULL,  
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT ESTADOS_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)USING INDEX (CREATE INDEX ESTADOS_ID_ESTADO_IDX ON FIDE_ESTADOS_TB (ID_ESTADO)),
    CONSTRAINT ESTADOS_ESTADO_UNQ UNIQUE(ESTADO)
   );
   
   CREATE OR REPLACE TRIGGER FIDE_ID_ESTADO_TRG
    BEFORE INSERT ON FIDE_ESTADOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ESTADO IS NULL THEN
            SELECT ID_ESTADO_SEQ.NEXTVAL
            INTO :NEW.ID_ESTADO
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------   
    /*CREATE SEQUENCE ID_SEDE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_SEDES_TB (	
    ID_SEDE NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL, 
    CIUDAD VARCHAR2(50)NOT NULL,
    DIRECCION VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT SEDES_ID_SEDE_PK PRIMARY KEY (ID_SEDE)USING INDEX (CREATE INDEX SEDES_ID_SEDE_IDX ON FIDE_SEDES_TB (ID_SEDE)),
    CONSTRAINT SEDES_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_SEDE_TRG
    BEFORE INSERT ON FIDE_SEDES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_SEDE IS NULL THEN
            SELECT ID_SEDE_SEQ.NEXTVAL
            INTO :NEW.ID_SEDE
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_PUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_PUESTOS_TB (	
    ID_PUESTO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL, 
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT PUESTOS_ID_PUESTO_PK PRIMARY KEY (ID_PUESTO)USING INDEX (CREATE INDEX PUESTOS_ID_PUESTO_IDX ON FIDE_PUESTOS_TB (ID_PUESTO)),
    CONSTRAINT PUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_PUESTO_TRG
    BEFORE INSERT ON FIDE_PUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_PUESTO IS NULL THEN
            SELECT ID_PUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_PUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_SERVICIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_SERVICIOS_TB (	
    ID_SERVICIO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL, 
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT SERVICIOS_ID_SERVICIO_PK PRIMARY KEY (ID_SERVICIO)USING INDEX (CREATE INDEX SERVICIOS_ID_SERVICIO_IDX ON FIDE_SERVICIOS_TB (ID_SERVICIO)),
    CONSTRAINT SERVICIOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_SERVICIO_TRG
    BEFORE INSERT ON FIDE_SERVICIOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_SERVICIO IS NULL THEN
            SELECT ID_SERVICIO_SEQ.NEXTVAL
            INTO :NEW.ID_SERVICIO
            FROM DUAL;
        END IF;
    END;*/
---------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_CATEGORIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_CATEGORIAS_TB (	
    ID_CATEGORIA NUMBER, 
	DESCRIPCION VARCHAR2(100)NOT NULL,
    IMAGEN VARCHAR2(1024)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT CATEGORIAS_ID_CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA)USING INDEX (CREATE INDEX CATEGORIAS_ID_CATEGORIA_IDX ON FIDE_CATEGORIAS_TB (ID_CATEGORIA)),
    CONSTRAINT CATEGORIAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_CATEGORIA_TRG
    BEFORE INSERT ON FIDE_CATEGORIAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CATEGORIA IS NULL THEN
            SELECT ID_CATEGORIA_SEQ.NEXTVAL
            INTO :NEW.ID_CATEGORIA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_TIPO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_TIPOS_TB (	
    ID_TIPO NUMBER, 
	NOMBRE VARCHAR2(100)NOT NULL,
	ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT TIPOS_ID_TIPO_PK PRIMARY KEY (ID_TIPO)USING INDEX (CREATE INDEX TIPOS_ID_TIPO_IDX ON FIDE_TIPOS_TB (ID_TIPO)),
    CONSTRAINT TIPOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_TIPO_TRG
    BEFORE INSERT ON FIDE_TIPOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_TIPO IS NULL THEN
            SELECT ID_TIPO_SEQ.NEXTVAL
            INTO :NEW.ID_TIPO
            FROM DUAL;
        END IF;
    END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_EMPLEADO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_EMPLEADOS_TB (	
    ID_EMPLEADO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    APELLIDO VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
    CORREO VARCHAR2(100)NOT NULL,
    FECHA_CONTRATO DATE NOT NULL,
    SALARIO VARCHAR2(500) NULL,
	ESTADO NUMBER(1) NOT NULL,
    ID_PUESTO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    CONSTRAINT EMPLEADOS_ID_EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO)USING INDEX (CREATE INDEX EMPLEADOS_ID_EMPLEADO_IDX ON FIDE_EMPLEADOS_TB (ID_EMPLEADO)),
    CONSTRAINT EMPLEADOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT EMPLEADOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT EMPLEADOS_ID_PUESTO_FK FOREIGN KEY (ID_PUESTO)REFERENCES FIDE_PUESTOS_TB (ID_PUESTO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_EMPLEADO_TRG
    BEFORE INSERT ON FIDE_EMPLEADOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_EMPLEADO IS NULL THEN
            SELECT ID_EMPLEADO_SEQ.NEXTVAL
            INTO :NEW.ID_EMPLEADO
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE TABLE FIDE_USUARIOS_TB (	
    ID_USUARIO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    APELLIDO VARCHAR2(50)NOT NULL,
    TELEFONO VARCHAR2(50)NOT NULL,
    CORREO VARCHAR2(100)NOT NULL,
    USERNAME VARCHAR2(50)NOT NULL,
    UPASSWORD VARCHAR2(500)NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT USUARIOS_ID_USUARIO_PK PRIMARY KEY(ID_USUARIO)USING INDEX (CREATE INDEX USUARIOS_ID_USUARIO_IDX ON FIDE_USUARIOS_TB (ID_USUARIO)),
    CONSTRAINT USUARIOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT USUARIOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));*/
----------------------------------------------------------------------------------------------------------------------------------------------------
    /*CREATE SEQUENCE ID_ROL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_ROLES_TB (	
    ID_ROL NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY (ID_ROL)USING INDEX (CREATE INDEX ROLES_ID_ROL_IDX ON FIDE_ROLES_TB (ID_ROL)),
    CONSTRAINT ROLES_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO)REFERENCES FIDE_USUARIOS_TB (ID_USUARIO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_ROL_TRG
    BEFORE INSERT ON FIDE_ROLES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ROL IS NULL THEN
            SELECT ID_ROL_SEQ.NEXTVAL
            INTO :NEW.ID_ROL
            FROM DUAL;
        END IF;
    END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MARCA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MARCAS_TB (	
    ID_MARCA NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MARCAS_ID_MARCA_PK PRIMARY KEY (ID_MARCA)USING INDEX (CREATE INDEX MARCAS_ID_MARCA_IDX ON FIDE_MARCAS_TB (ID_MARCA)),
    CONSTRAINT MARCAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MARCA_TRG
    BEFORE INSERT ON FIDE_MARCAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MARCA IS NULL THEN
            SELECT ID_MARCA_SEQ.NEXTVAL
            INTO :NEW.ID_MARCA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MARCA_REPUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MARCAS_REPUESTOS_TB (	
    ID_MARCA_REPUESTO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MARCAS_ID_MARCA_REPUESTO_PK PRIMARY KEY (ID_MARCA_REPUESTO)USING INDEX (CREATE INDEX MARCAS_ID_MARCA_REPUESTO_IDX ON FIDE_MARCAS_REPUESTOS_TB (ID_MARCA_REPUESTO)),
    CONSTRAINT MARCAS_REPUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MARCA_REPUESTO_TRG
    BEFORE INSERT ON FIDE_MARCAS_REPUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MARCA_REPUESTO IS NULL THEN
            SELECT ID_MARCA_REPUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_MARCA_REPUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_MODELO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_MODELOS_TB (	
    ID_MODELO NUMBER, 
	NOMBRE VARCHAR2(50)NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT MODELOS_ID_MODELO_PK PRIMARY KEY (ID_MODELO)USING INDEX (CREATE INDEX MODELOS_ID_MODELO_IDX ON FIDE_MODELOS_TB (ID_MODELO)),
    CONSTRAINT MODELOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT MODELOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_MODELO_TRG
    BEFORE INSERT ON FIDE_MODELOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_MODELO IS NULL THEN
            SELECT ID_MODELO_SEQ.NEXTVAL
            INTO :NEW.ID_MODELO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE TABLE FIDE_VEHICULOS_TB (	
    PLACA VARCHAR2(30), 
	ID_MARCA NUMBER NOT NULL,
    ID_MODELO NUMBER NOT NULL,
    ID_TIPO NUMBER NOT NULL,
    AÑO NUMBER(4) NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT VEHICULOS_PLACA_PK PRIMARY KEY(PLACA)USING INDEX (CREATE INDEX VEHICULOS_PLACA_IDX ON FIDE_VEHICULOS_TB (PLACA)),
    CONSTRAINT VEHICULOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO),
    CONSTRAINT VEHICULOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT VEHICULOS_ID_MARCA_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_TB (ID_MARCA),
    CONSTRAINT VEHICULOS_ID_MODELO_FK FOREIGN KEY (ID_MODELO)REFERENCES FIDE_MODELOS_TB (ID_MODELO),
    CONSTRAINT VEHICULOS_ID_TIPO_FK FOREIGN KEY (ID_TIPO)REFERENCES FIDE_TIPOS_TB (ID_TIPO),
    CONSTRAINT VEHICULOS_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO)REFERENCES FIDE_USUARIOS_TB (ID_USUARIO));*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_CITA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_CITAS_TB (	
    ID_CITA NUMBER, 
	PLACA VARCHAR2(30)NOT NULL,
    FECHA DATE NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT CITAS_ID_CITA_PK PRIMARY KEY (ID_CITA)USING INDEX (CREATE INDEX CITAS_ID_CITA_IDX ON FIDE_CITAS_TB (ID_CITA)),
    CONSTRAINT CITAS_PLACA_FK FOREIGN KEY (PLACA)REFERENCES FIDE_VEHICULOS_TB (PLACA),
    CONSTRAINT CITAS_ID_SERVICIO_FK FOREIGN KEY (ID_SERVICIO)REFERENCES FIDE_SERVICIOS_TB (ID_SERVICIO),
    CONSTRAINT CITAS_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES FIDE_EMPLEADOS_TB (ID_EMPLEADO),
    CONSTRAINT CITAS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT CITAS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_CITA_TRG
    BEFORE INSERT ON FIDE_CITAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CITA IS NULL THEN
            SELECT ID_CITA_SEQ.NEXTVAL
            INTO :NEW.ID_CITA
            FROM DUAL;
        END IF;
    END;*/
--------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_REPUESTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_REPUESTOS_TB (	
    ID_REPUESTO NUMBER, 
	IMAGEN VARCHAR2(1024) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER(1) NOT NULL,
    CONSTRAINT REPUESTOS_ID_REPUESTO_PK PRIMARY KEY (ID_REPUESTO)USING INDEX (CREATE INDEX REPUESTOS_ID_REPUESTO_IDX ON FIDE_REPUESTOS_TB (ID_REPUESTO)),
    CONSTRAINT REPUESTOS_ID_MARCA_REPUESTO_FK FOREIGN KEY (ID_MARCA)REFERENCES FIDE_MARCAS_REPUESTOS_TB (ID_MARCA_REPUESTO),
    CONSTRAINT REPUESTOS_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA)REFERENCES FIDE_CATEGORIAS_TB (ID_CATEGORIA),
    CONSTRAINT REPUESTOS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT REPUESTOS_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_REPUESTO_TRG
    BEFORE INSERT ON FIDE_REPUESTOS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_REPUESTO IS NULL THEN
            SELECT ID_REPUESTO_SEQ.NEXTVAL
            INTO :NEW.ID_REPUESTO
            FROM DUAL;
        END IF;
    END;*/
------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_ORDEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_ORDENES_TB (	
    ID_ORDEN NUMBER, 
	ID_CITA NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    COMENTARIOS VARCHAR2(1500) NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SEDE NUMBER NOT NULL,
    ESTADO NUMBER NOT NULL,
    CONSTRAINT ORDENES_ID_ORDEN_PK PRIMARY KEY (ID_ORDEN)USING INDEX (CREATE INDEX ORDENES_ID_ORDEN_IDX ON FIDE_ORDENES_TB (ID_ORDEN)),
    CONSTRAINT ORDENES_ID_CITA_FK FOREIGN KEY (ID_CITA)REFERENCES FIDE_CITAS_TB (ID_CITA),
    CONSTRAINT ORDENES_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES FIDE_EMPLEADOS_TB (ID_EMPLEADO),
    CONSTRAINT ORDENES_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE),
    CONSTRAINT ORDENES_ESTADO_FK FOREIGN KEY (ESTADO)REFERENCES FIDE_ESTADOS_TB (ESTADO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_ORDEN_TRG
    BEFORE INSERT ON FIDE_ORDENES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ORDEN IS NULL THEN
            SELECT ID_ORDEN_SEQ.NEXTVAL
            INTO :NEW.ID_ORDEN
            FROM DUAL;
        END IF;
    END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_FACTURA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_FACTURAS_TB (	
    ID_FACTURA NUMBER, 
	ID_SEDE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    PRECIO_FINAL NUMBER NOT NULL,
    CONSTRAINT FACTURAS_ID_FACTURA_PK PRIMARY KEY (ID_FACTURA)USING INDEX (CREATE INDEX FACTURAS_ID_FACTURA_IDX ON FIDE_FACTURAS_TB (ID_FACTURA)),
    CONSTRAINT FACTURAS_ID_SEDE_FK FOREIGN KEY (ID_SEDE)REFERENCES FIDE_SEDES_TB (ID_SEDE));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_FACTURA_TRG
    BEFORE INSERT ON FIDE_FACTURAS_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_FACTURA IS NULL THEN
            SELECT ID_FACTURA_SEQ.NEXTVAL
            INTO :NEW.ID_FACTURA
            FROM DUAL;
        END IF;
    END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE SEQUENCE ID_DETALLE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE TABLE FIDE_DETALLES_TB (	
    ID_DETALLE NUMBER, 
	ID_FACTURA NUMBER NOT NULL,
    ID_ORDEN NUMBER NOT NULL,
    ID_REPUESTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER NOT NULL,
    CONSTRAINT DETALLES_ID_DETALLE_PK PRIMARY KEY (ID_DETALLE)USING INDEX (CREATE INDEX DETALLES_ID_DETALLE_IDX ON FIDE_DETALLES_TB (ID_DETALLE)),
    CONSTRAINT DETALLES_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA)REFERENCES FIDE_FACTURAS_TB (ID_FACTURA),
    CONSTRAINT DETALLES_ID_ORDEN_FK FOREIGN KEY (ID_ORDEN)REFERENCES FIDE_ORDENES_TB (ID_ORDEN),
    CONSTRAINT DETALLES_ID_REPUESTO_FK FOREIGN KEY (ID_REPUESTO)REFERENCES FIDE_REPUESTOS_TB (ID_REPUESTO));
    
    CREATE OR REPLACE TRIGGER FIDE_ID_DETALLE_TRG
    BEFORE INSERT ON FIDE_DETALLES_TB
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_DETALLE IS NULL THEN
            SELECT ID_DETALLE_SEQ.NEXTVAL
            INTO :NEW.ID_DETALLE
            FROM DUAL;
        END IF;
    END;*/   
---------------------------------------------------------------------------------------------------------------------------------------------------------------------    
INSERT INTO FIDE_ESTADOS_TB (DESCRIPCION, ESTADO) VALUES ('Activo', 1);
INSERT INTO FIDE_ESTADOS_TB (DESCRIPCION, ESTADO) VALUES ('Inactivo', 0);
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller TF', 'San Jose', 'Bajo Piuses', '89984395', 1);

INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller Los Amigos', 'Heredia', 'El Carao', '72063542', 1);

INSERT INTO FIDE_SEDES_TB (NOMBRE, CIUDAD, DIRECCION, TELEFONO, ESTADO)
VALUES ('Taller Sebas', 'Alajuela', 'San Rafael', '88888888', 1);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_USUARIOS_TB (ID_USUARIO,NOMBRE, APELLIDO, TELEFONO, CORREO, USERNAME, UPASSWORD, ID_SEDE, ESTADO)
VALUES (115470088,'Hector', 'Hernandez', '72063542', 'hhernan93vargas@gmail.com', 'hhernan', '$2a$12$pmBd.ZI04Cw/Oa1SKRXX1ead2W1sVn/1avq6GBjc76Tfaf1PYW4re', 1, 1);
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO FIDE_ROLES_TB (NOMBRE, ID_USUARIO)
VALUES ('ROLE_ADMIN', 115470088);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_ROLES_TB_ADD_ROL_SP (RNAME IN VARCHAR2,IDUSER IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_ROLES_TB (NOMBRE,ID_USUARIO) VALUES (RNAME,IDUSER);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_ADD_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_ROLES_TB_DELETE_ROL_SP (IDU IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_ROLES_TB WHERE ID_USUARIO=IDU;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_DELETE_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_DELETE_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_ROLES_TB_DELETE_ROLBYID_SP (RID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_ROLES_TB WHERE ID_ROL=RID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_DELETE_ROLBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_DELETE_ROLBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_ROLES_TB_GET_ROLES_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_ROL,NOMBRE,ID_USUARIO FROM FIDE_ROLES_TB;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_GET_ROLES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_ROLES_TB_GET_ROL_SP (RID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_ROL,NOMBRE,ID_USUARIO FROM FIDE_ROLES_TB WHERE ID_ROL=RID;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_GET_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_ROLES_TB_UPDATE_ROL_SP (RID IN NUMBER,NOMB IN VARCHAR2,USID IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    UPDATE FIDE_ROLES_TB SET NOMBRE=NOMB,ID_USUARIO=USID WHERE ID_ROL=RID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ROLES_TB_UPDATE_ROL_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_TB_ADD_USUARIO_SP (USID IN NUMBER,UNAME IN VARCHAR2,PASS IN VARCHAR2,UNOM IN VARCHAR2,APELL IN VARCHAR2,CORRE IN VARCHAR2,TEL IN VARCHAR2,IDS IN NUMBER,EST IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    INSERT INTO FIDE_USUARIOS_TB (ID_USUARIO,USERNAME, UPASSWORD,NOMBRE, APELLIDO,CORREO,TELEFONO,ID_SEDE,ESTADO) VALUES (USID,UNAME,PASS,UNOM, APELL,CORRE,TEL,IDS,EST);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_ADD_USUARIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_TB_DELETE_USUARIO_SP (USEID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    FIDE_ROLES_TB_DELETE_ROL_SP(USEID);
    DELETE FROM FIDE_USUARIOS_TB WHERE ID_USUARIO=USEID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_DELETE_USUARIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_TB_UPDATE_USUARIO_SP (USERID IN NUMBER,USNAM IN VARCHAR2,CONTRAS IN VARCHAR2,NOMBR IN VARCHAR2,APELLI IN VARCHAR2,MAIL IN VARCHAR2,PHONE IN VARCHAR2,IDS IN NUMBER,ACTV IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    UPDATE FIDE_USUARIOS_TB SET USERNAME=USNAM, UPASSWORD=CONTRAS,NOMBRE=NOMBR, APELLIDO=APELLI,CORREO=MAIL, TELEFONO=PHONE,ID_SEDE=IDS,ESTADO=ACTV WHERE ID_USUARIO=USERID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_UPDATE_USUARIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE,ESTADO FROM FIDE_USUARIOS_TB;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOSBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE,ESTADO FROM FIDE_USUARIOS_TB WHERE ESTADO=1;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOSBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOBYID_SP (UID IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE ID_USUARIO = UID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USUARIOBYUSERNAME_SP (UNAME IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE USERNAME = UNAME;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYUSERNAME_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USUARIOBYUSERNAME_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USERNAMEANDPASSWORD_SP(UNAME IN VARCHAR2, PASS IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE USERNAME = UNAME and UPASSWORD = PASS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEANDPASSWORD_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEANDPASSWORD_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_USERNAMEORCORREO_SP(UNAME IN VARCHAR2, CORRE IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB
   WHERE USERNAME = UNAME OR CORREO = CORRE;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEORCORREO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_USERNAMEORCORREO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE FUNCTION FIDE_USUARIOS_TB_USUARIO_EXISTE_FN (UNAME IN VARCHAR2, CORRE IN VARCHAR2) RETURN NUMBER
IS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    FOR DATOS IN (SELECT ID_USUARIO, USERNAME, UPASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO,ID_SEDE, ESTADO FROM FIDE_USUARIOS_TB) LOOP
        IF DATOS.USERNAME = UNAME OR DATOS.CORREO = CORRE THEN
            RETURN 1; -- TRUE
        END IF;
    END LOOP;
    RETURN 0; -- FALSE
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );
        RETURN -1;

    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );
        RETURN -1;
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_ROLES_SP(UID IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT NOMBRE FROM FIDE_ROLES_TB
   WHERE ID_USUARIO = UID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );

    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_USUARIO_EXISTE_FN',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_USUARIOS_TB_GET_SEDES_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB
   WHERE ESTADO=1;
EXCEPTION
     WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_USUARIOS_TB_GET_SEDES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SEDES_TB_GET_SEDESBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SEDES_TB_GET_SEDES_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*Create or replace PROCEDURE FIDE_SEDES_TB_GET_SEDESBYID_SP (IDS IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SEDE,NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO FROM FIDE_SEDES_TB
   WHERE ID_SEDE = IDS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDESBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_GET_SEDESBYID_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_SEDES_TB_ADD_SEDE_SP (NOMB IN VARCHAR2,CIT IN VARCHAR2,DIR IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_SEDES_TB (NOMBRE,CIUDAD,DIRECCION,TELEFONO,ESTADO) VALUES (NOMB,CIT,DIR,TEL,EST);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_ADD_SEDE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_SEDES_TB_DELETE_SEDE_SP (IDS IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_SEDES_TB WHERE ID_SEDE=IDS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_DELETE_SEDE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SEDES_TB_UPDATE_SEDE_SP (IDS IN NUMBER,NOMB IN VARCHAR2,CIT IN VARCHAR2,DIR IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_SEDES_TB SET NOMBRE=NOMB,CIUDAD=CIT,DIRECCION=DIR,TELEFONO=TEL,ESTADO=EST WHERE ID_SEDE=IDS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SEDES_TB_UPDATE_SEDE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CATEGORIAS_TB_GET_CATEGORIA_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,IMAGEN,ESTADO FROM FIDE_CATEGORIAS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CATEGORIAS_TB_GET_CATEGORIABYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,IMAGEN,ESTADO FROM FIDE_CATEGORIAS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_CATEGORIABYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CATEGORIAS_TB_GET_ONE_CATEGORIA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,IMAGEN,ESTADO FROM FIDE_CATEGORIAS_TB WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_ONE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_GET_ONE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------- 
/*CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_TB_ADD_CATEGORIA_SP (DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_CATEGORIAS_TB (DESCRIPCION,IMAGEN,ESTADO) VALUES (DESCRIP,IMG,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_ADD_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_TB_DELETE_CATEGORIA_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_CATEGORIAS_TB WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_DELETE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_TB_UPDATE_CATEGORIA_SP (CID IN NUMBER,DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_CATEGORIAS_TB SET DESCRIPCION = DESCRIP ,IMAGEN = IMG,ESTADO = ACT WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CATEGORIAS_TB_UPDATE_CATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SERVICIOS_TB_GET_SERVICIOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SERVICIO,NOMBRE,ESTADO FROM FIDE_SERVICIOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 ----------------------------------------------------------------------------------------------------------------------------------------------------------------
 /*create or replace PROCEDURE FIDE_SERVICIOS_TB_GET_SERVICIOSBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SERVICIO,NOMBRE,ESTADO FROM FIDE_SERVICIOS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIOSBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_SERVICIOS_TB_GET_SERVICIO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_SERVICIO,NOMBRE,ESTADO FROM FIDE_SERVICIOS_TB WHERE ID_SERVICIO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_GET_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_TB_ADD_SERVICIO_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_SERVICIOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_ADD_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_TB_DELETE_SERVICIO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_SERVICIOS_TB WHERE ID_SERVICIO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_DELETE_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_TB_UPDATE_SERVICIO_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_SERVICIOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_SERVICIO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_SERVICIOS_TB_UPDATE_SERVICIO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_TIPOS_TB_GET_TIPOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_TIPO,NOMBRE,ESTADO FROM FIDE_TIPOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 -------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_TIPOS_TB_GET_TIPOSBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_TIPO,NOMBRE,ESTADO FROM FIDE_TIPOS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPOSBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_TIPOS_TB_GET_TIPO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_TIPO,NOMBRE,ESTADO FROM FIDE_TIPOS_TB WHERE ID_TIPO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_GET_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_TIPOS_TB_ADD_TIPO_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_TIPOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_ADD_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_TIPOS_TB_DELETE_TIPO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_TIPOS_TB WHERE ID_TIPO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_DELETE_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_TIPOS_TB_UPDATE_TIPO_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_TIPOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_TIPO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_TIPOS_TB_UPDATE_TIPO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_PUESTOS_TB_GET_PUESTOSBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_PUESTO,NOMBRE,ESTADO FROM FIDE_PUESTOS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTOSBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_PUESTOS_TB_GET_PUESTOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_PUESTO,NOMBRE,ESTADO FROM FIDE_PUESTOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_PUESTOS_TB_GET_PUESTO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_PUESTO,NOMBRE,ESTADO FROM FIDE_PUESTOS_TB WHERE ID_PUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_GET_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_PUESTOS_TB_ADD_PUESTO_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_PUESTOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_ADD_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_PUESTOS_TB_DELETE_PUESTO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_PUESTOS_TB WHERE ID_PUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_DELETE_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_PUESTOS_TB_UPDATE_PUESTO_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_PUESTOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_PUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_PUESTOS_TB_UPDATE_PUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_TB_GET_MARCASBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA,NOMBRE,ESTADO FROM FIDE_MARCAS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCASBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_TB_GET_MARCAS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA,NOMBRE,ESTADO FROM FIDE_MARCAS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCAS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_TB_GET_MARCA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA,NOMBRE,ESTADO FROM FIDE_MARCAS_TB WHERE ID_MARCA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_GET_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_TB_ADD_MARCA_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_MARCAS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_ADD_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_TB_DELETE_MARCA_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_MARCAS_TB WHERE ID_MARCA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_DELETE_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_TB_UPDATE_MARCA_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_MARCAS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_MARCA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_TB_UPDATE_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MODELOS_TB_GET_MODELOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MODELO,NOMBRE,ID_MARCA,ESTADO FROM FIDE_MODELOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MODELOS_TB_GET_MODELO_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MODELO,NOMBRE,ID_MARCA,ESTADO FROM FIDE_MODELOS_TB WHERE ID_MODELO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MODELOS_TB_ADD_MODELO_SP (NOM IN VARCHAR2,MID IN NUMBER,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_MODELOS_TB (NOMBRE,ID_MARCA,ESTADO) VALUES (NOM,MID,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_ADD_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MODELOS_TB_DELETE_MODELO_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_MODELOS_TB WHERE ID_MODELO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_DELETE_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MODELOS_TB_UPDATE_MODELO_SP (CID IN NUMBER,NOM IN VARCHAR2,MID IN NUMBER, ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_MODELOS_TB SET NOMBRE=NOM,ID_MARCA=MID,ESTADO=ACT WHERE ID_MODELO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_UPDATE_MODELO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MODELOS_TB_GET_MODELOSBYMARCA_SP (MID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MODELO,NOMBRE,ID_MARCA,ESTADO FROM FIDE_MODELOS_TB WHERE ID_MARCA=MID AND ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MODELOS_TB_GET_MODELOSBYMARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_EMPLEADOS_TB_GET_EMPLEADOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_EMPLEADO,NOMBRE,APELLIDO,TELEFONO,CORREO,FECHA_CONTRATO,DESCRIPT(SALARIO) as SALARIO,ID_PUESTO,ID_SEDE,ESTADO,USERNAME FROM FIDE_EMPLEADOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_GET_EMPLEADOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/* create or replace PROCEDURE FIDE_EMPLEADOS_TB_GET_EMPLEADOSBYUSERNAME_SP (UNAME IN VARCHAR2,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_EMPLEADO,NOMBRE,APELLIDO,TELEFONO,CORREO,FECHA_CONTRATO,DESCRIPT(SALARIO)as SALARIO,ID_PUESTO,ID_SEDE,ESTADO,USERNAME FROM FIDE_EMPLEADOS_TB WHERE UPPER(USERNAME)=UPPER(UNAME);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_GET_EMPLEADOSBYUSERNAME_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_EMPLEADOS_TB_GET_EMPLEADOSBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_EMPLEADO,NOMBRE,APELLIDO,TELEFONO,CORREO,FECHA_CONTRATO,DESCRIPT(SALARIO)as SALARIO,ID_PUESTO,ID_SEDE,ESTADO,USERNAME FROM FIDE_EMPLEADOS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_GET_EMPLEADOSBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_EMPLEADOS_TB_GET_EMPLEADO_SP (EID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_EMPLEADO,NOMBRE,APELLIDO,TELEFONO,CORREO,FECHA_CONTRATO,DESCRIPT(SALARIO)as SALARIO,ID_PUESTO,ID_SEDE,ESTADO,USERNAME FROM FIDE_EMPLEADOS_TB WHERE ID_EMPLEADO=EID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_GET_EMPLEADO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_GET_EMPLEADO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_EMPLEADOS_TB_ADD_EMPLEADO_SP (NOM IN VARCHAR2,APE IN VARCHAR2,TEL IN VARCHAR2,CORRE IN VARCHAR2,FECH IN DATE,SAL IN VARCHAR2,IDP IN NUMBER,IDS IN NUMBER,ACT IN NUMBER,UNAME IN VARCHAR2) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_EMPLEADOS_TB (NOMBRE,APELLIDO,TELEFONO,CORREO,FECHA_CONTRATO,SALARIO,ID_PUESTO,ID_SEDE,ESTADO,USERNAME) VALUES (NOM,APE,TEL,CORRE,FECH,ENCRIPT(SAL),IDP,IDS,ACT,UNAME);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_ADD_EMPLEADO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_EMPLEADOS_TB_DELETE_EMPLEADO_SP (EID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_EMPLEADOS_TB WHERE ID_EMPLEADO=EID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_DELETE_EMPLEADO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_EMPLEADOS_TB_UPDATE_EMPLEADO_SP (EID IN NUMBER,NOM IN VARCHAR2,APE IN VARCHAR2,TEL IN VARCHAR2,CORRE IN VARCHAR2,FECH IN DATE,SAL IN VARCHAR2,IDP IN NUMBER,IDS IN NUMBER,ACT IN NUMBER,UNAME IN VARCHAR2) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_EMPLEADOS_TB SET NOMBRE=NOM,APELLIDO=APE,TELEFONO=TEL,CORREO=CORRE,FECHA_CONTRATO=FECH,SALARIO=ENCRIPT(SAL),ID_PUESTO=IDP,ID_SEDE=IDS,ESTADO=ACT,USERNAME=UNAME WHERE ID_EMPLEADO=EID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_EMPLEADOS_TB_UPDATE_EMPLEADO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_VEHICULOS_TB_GET_VEHICULOS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT PLACA,ID_MARCA,ID_MODELO,ID_TIPO,ANO,ID_SEDE,ID_USUARIO,ESTADO FROM FIDE_VEHICULOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_GET_VEHICULOS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/* create or replace PROCEDURE FIDE_VEHICULOS_TB_GET_VEHICULOSBYUSER_SP (USID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT PLACA,ID_MARCA,ID_MODELO,ID_TIPO,ANO,ID_SEDE,ID_USUARIO,ESTADO FROM FIDE_VEHICULOS_TB WHERE ID_USUARIO=USID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_GET_VEHICULOSBYUSER_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/* create or replace PROCEDURE FIDE_VEHICULOS_TB_GET_VEHICULOSBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT PLACA,ID_MARCA,ID_MODELO,ID_TIPO,ANO,ID_SEDE,ID_USUARIO,ESTADO FROM FIDE_VEHICULOS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_GET_VEHICULOSBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_VEHICULOS_TB_GET_VEHICULOSBYUSERANDSTATE_SP (USID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT PLACA,ID_MARCA,ID_MODELO,ID_TIPO,ANO,ID_SEDE,ID_USUARIO,ESTADO FROM FIDE_VEHICULOS_TB WHERE ID_USUARIO=USID AND ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_GET_VEHICULOSBYUSERANDSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_VEHICULOS_TB_GET_VEHICULO_SP (PLACA IN VARCHAR2,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT PLACA,ID_MARCA,ID_MODELO,ID_TIPO,ANO,ID_SEDE,ID_USUARIO,ESTADO FROM FIDE_VEHICULOS_TB WHERE PLACA=PLACA;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_GET_VEHICULO_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_GET_VEHICULO_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_VEHICULOS_TB_ADD_VEHICULO_SP (PLAC IN VARCHAR2,MID IN NUMBER,IDM IN NUMBER,TID IN NUMBER,ANO IN NUMBER,IDS IN NUMBER,USID IN NUMBER,ACT IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_VEHICULOS_TB (PLACA,ID_MARCA,ID_MODELO,ID_TIPO,ANO,ID_SEDE,ID_USUARIO,ESTADO) VALUES (PLAC,MID,IDM,TID,ANO,IDS,USID,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_ADD_VEHICULO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_VEHICULOS_TB_DELETE_VEHICULO_SP (PLAC IN VARCHAR2) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
    v_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM FIDE_CITAS_TB
    WHERE PLACA = PLAC AND ESTADO=1;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El vehículo tiene citas asociadas y no se puede eliminar.');
    ELSE
       DELETE FROM FIDE_VEHICULOS_TB WHERE PLACA=PLAC;
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_DELETE_VEHICULO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_VEHICULOS_TB_UPDATE_VEHICULO_SP (PLAC IN VARCHAR2,MID IN NUMBER,IDM IN NUMBER,TID IN NUMBER,LLEAR IN NUMBER,IDS IN NUMBER,USID IN NUMBER,ACT IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_VEHICULOS_TB SET ID_MARCA = MID,ID_MODELO = IDM,ID_TIPO = TID,ANO = LLEAR,ID_SEDE = IDS,ID_USUARIO = USID,ESTADO = ACT WHERE TRIM(UPPER(PLACA)) = TRIM(UPPER(PLAC));
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_VEHICULOS_TB_UPDATE_VEHICULO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CITAS_TB_GET_CITAS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CITA,PLACA,FECHA,ID_SERVICIO,ID_EMPLEADO,ID_SEDE,ESTADO FROM FIDE_CITAS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_GET_CITAS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CITAS_TB_GET_CITASBYUSER_SP (USID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CITA,PLACA,FECHA,ID_SERVICIO,ID_EMPLEADO,ID_SEDE,ESTADO FROM FIDE_CITAS_TB 
   WHERE ESTADO=1 AND PLACA in (SELECT PLACA FROM FIDE_VEHICULOS_TB WHERE ID_USUARIO=USID);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_GET_CITASBYUSER_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 /*create or replace PROCEDURE FIDE_CITAS_TB_GET_CITASBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CITA,PLACA,FECHA,ID_SERVICIO,ID_EMPLEADO,ID_SEDE,ESTADO FROM FIDE_CITAS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_GET_CITASBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_CITAS_TB_GET_CITA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_CITA,PLACA,FECHA,ID_SERVICIO,ID_EMPLEADO,ID_SEDE,ESTADO FROM FIDE_CITAS_TB WHERE ID_CITA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_GET_CITA_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_GET_CITA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CITAS_TB_ADD_CITA_SP (PLAC IN VARCHAR2,FECH IN DATE,SERID IN NUMBER,EMPID IN NUMBER,IDSED IN NUMBER,ACT IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_CITAS_TB (PLACA,FECHA,ID_SERVICIO,ID_EMPLEADO,ID_SEDE,ESTADO) VALUES (PLAC,FECH,SERID,EMPID,IDSED,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_ADD_CITA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CITAS_TB_DELETE_CITA_SP (CID IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_CITAS_TB WHERE ID_CITA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_DELETE_CITA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_CITAS_TB_UPDATE_CITA_SP (CID IN NUMBER,PLAC IN VARCHAR2,FECH IN DATE,SERID IN NUMBER,EMPID IN NUMBER,IDSED IN NUMBER,ACT IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_CITAS_TB SET PLACA=PLAC,FECHA=FECH,ID_SERVICIO=SERID,ID_EMPLEADO=EMPID,ID_SEDE=IDSED,ESTADO=ACT WHERE ID_CITA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_CITAS_TB_UPDATE_CITA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_ORDENES_TB_GET_ORDENES_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_ORDEN,ID_CITA,FECHA,COMENTARIOS,ID_EMPLEADO,ID_SEDE,ESTADO FROM FIDE_ORDENES_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ORDENES_TB_GET_ORDENES_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_ORDENES_TB_GET_ORDEN_SP (OID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_ORDEN,ID_CITA,FECHA,COMENTARIOS,ID_EMPLEADO,ID_SEDE,ESTADO FROM FIDE_ORDENES_TB WHERE ID_ORDEN=OID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ORDENES_TB_GET_ORDEN_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ORDENES_TB_GET_ORDEN_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_ORDENES_TB_ADD_ORDEN_SP (CID IN NUMBER,FECH IN DATE,COMS IN VARCHAR2,EMPID IN NUMBER,IDSED IN NUMBER,ACT IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_ORDENES_TB (ID_CITA,FECHA,COMENTARIOS,ID_EMPLEADO,ID_SEDE,ESTADO) VALUES (CID,FECH,COMS,EMPID,IDSED,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ORDENES_TB_ADD_ORDEN_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_ORDENES_TB_DELETE_ORDEN_SP (OID IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_ORDENES_TB WHERE ID_ORDEN=OID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ORDENES_TB_DELETE_ORDEN_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_ORDENES_TB_UPDATE_ORDEN_SP (OID IN NUMBER,CID IN NUMBER,FECH IN DATE,COMS IN VARCHAR2,EMPID IN NUMBER,IDSED IN NUMBER,ACT IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_ORDENES_TB SET ID_CITA=CID,FECHA=FECH,COMENTARIOS=COMS,ID_EMPLEADO=EMPID,ID_SEDE=IDSED,ESTADO=ACT WHERE ID_ORDEN=OID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_ORDENES_TB_UPDATE_ORDEN_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE  PROCEDURE FIDE_FACTURAS_TB_ADD_FACTURA_SP (IDSED IN NUMBER,FECHA IN DATE,TOTAL IN NUMBER,USERID IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_FACTURAS_TB (ID_SEDE,FECHA,PRECIO_FINAL,ID_USUARIO) VALUES (IDSED,FECHA,TOTAL,USERID);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_FACTURAS_TB_ADD_FACTURA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_FACTURAS_TB_GET_FACTURABYDATE_SP (FECH IN DATE,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
   OPEN DATOS FOR SELECT ID_FACTURA FROM FIDE_FACTURAS_TB WHERE FECHA=FECH;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_FACTURAS_TB_GET_FACTURABYDATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_TB_UPDATE_FACTURA_SP (FID IN NUMBER,TOTL IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_FACTURAS_TB SET PRECIO_FINAL=TOTL WHERE ID_FACTURA=FID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_FACTURAS_TB_UPDATE_FACTURA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_DETALLES_TB_ADD_DETALLE_SP (IDFACT IN NUMBER,IDORD IN NUMBER,IDREP IN NUMBER,CANT IN NUMBER,PREC IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_DETALLES_TB (ID_FACTURA,ID_ORDEN,ID_REPUESTO,CANTIDAD,PRECIO_UNITARIO) VALUES (IDFACT,IDORD,IDREP,CANT,PREC);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_FACTURAS_TB_UPDATE_FACTURA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_REPUESTOS_TB_ADD_REPUESTO_SP (IMG IN VARCHAR2,NOM IN VARCHAR2,IDM IN NUMBER,PREC IN NUMBER,CANT IN NUMBER,CID IN NUMBER,IDSED IN NUMBER,EST IN NUMBER) AS 
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_REPUESTOS_TB (IMAGEN,NOMBRE,ID_MARCA,PRECIO,CANTIDAD,ID_CATEGORIA,ID_SEDE,ESTADO) VALUES (IMG,NOM,IDM,PREC,CANT,CID,IDSED,EST);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_REPUESTOS_TB_ADD_REPUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_REPUESTOS_TB_DELETE_REPUESTO_SP (RID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_REPUESTOS_TB WHERE ID_REPUESTO=RID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_REPUESTOS_TB_DELETE_REPUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_REPUESTOS_TB_GET_REPUESTOS_SP (DATOS OUT SYS_REFCURSOR)
AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
   OPEN DATOS FOR SELECT ID_REPUESTO,IMAGEN,NOMBRE,ID_MARCA,PRECIO,CANTIDAD,ID_CATEGORIA,ID_SEDE,ESTADO FROM FIDE_REPUESTOS_TB;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_FACTURAS_TB_GET_FACTURABYDATE_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_REPUESTOS_TB_UPDATE_REPUESTO_SP (RID IN NUMBER,IMG IN VARCHAR2,NOM IN VARCHAR2,MID IN NUMBER,PREC IN NUMBER,CANT IN NUMBER,CID IN NUMBER,IDSED IN NUMBER,EST IN NUMBER) AS
     VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_REPUESTOS_TB SET IMAGEN=IMG,NOMBRE=NOM,ID_MARCA=MID,PRECIO=PREC,CANTIDAD=CANT,ID_CATEGORIA=CID,ID_SEDE=IDSED,ESTADO=EST  WHERE ID_REPUESTO=RID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_REPUESTOS_TB_UPDATE_REPUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_REPUESTOS_TB_GET_REPUESTO_SP (RID IN NUMBER,DATOS OUT SYS_REFCURSOR)
AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
   OPEN DATOS FOR SELECT ID_REPUESTO,IMAGEN,NOMBRE,ID_MARCA,PRECIO,CANTIDAD,ID_CATEGORIA,ID_SEDE,ESTADO FROM FIDE_REPUESTOS_TB WHERE ID_REPUESTO=RID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_REPUESTOS_TB_GET_REPUESTO_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_REPUESTOS_TB_GET_REPUESTOSBYCATEGORIA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
   OPEN DATOS FOR SELECT ID_REPUESTO,IMAGEN,NOMBRE,ID_MARCA,PRECIO,CANTIDAD,ID_CATEGORIA,ID_SEDE,ESTADO FROM FIDE_REPUESTOS_TB WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_REPUESTOS_TB_GET_REPUESTOSBYCATEGORIA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_REPUESTOS_TB_GET_MARCASBYSTATE_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA_REPUESTO,NOMBRE,ESTADO FROM FIDE_MARCAS_REPUESTOS_TB WHERE ESTADO=1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_GET_MARCASBYSTATE_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_REPUESTOS_TB_GET_MARCAS_SP (DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA_REPUESTO,NOMBRE,ESTADO FROM FIDE_MARCAS_REPUESTOS_TB;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_GET_MARCAS_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
 --------------------------------------------------------------------------------------------------------------------------------------------------------------
/*create or replace PROCEDURE FIDE_MARCAS_REPUESTOS_TB_GET_MARCA_SP (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
 BEGIN
   OPEN DATOS FOR SELECT ID_MARCA_REPUESTO,NOMBRE,ESTADO FROM FIDE_MARCAS_REPUESTOS_TB WHERE ID_MARCA_REPUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_GET_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
    WHEN NO_DATA_FOUND THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_GET_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
 END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_REPUESTOS_TB_ADD_MARCA_SP (NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    INSERT INTO FIDE_MARCAS_REPUESTOS_TB (NOMBRE,ESTADO) VALUES (NOM,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_ADD_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
--------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_REPUESTOS_TB_DELETE_MARCA_SP (CID IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    DELETE FROM FIDE_MARCAS_REPUESTOS_TB WHERE ID_MARCA_REPUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_DELETE_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
------------------------------------------------------------------------------------------------------------------------------------------------------
/*CREATE OR REPLACE PROCEDURE FIDE_MARCAS_REPUESTOS_TB_UPDATE_MARCA_SP (CID IN NUMBER,NOM IN VARCHAR2,ACT IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(1024);
BEGIN
    UPDATE FIDE_MARCAS_REPUESTOS_TB SET NOMBRE=NOM,ESTADO = ACT WHERE ID_MARCA_REPUESTO=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO FIDE_ERRORES_TB VALUES (USER,'FIDE_MARCAS_REPUESTOS_TB_UPDATE_MARCA_SP',SYSDATE, VCOD || ' - '|| VMES );
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------
--  DDL for Function DESCRIPT
--------------------------------------------------------
/*CREATE OR REPLACE FUNCTION DESCRIPT (valor in varchar2)return varchar2 as
    V_key RAW(32):=UTL_RAW.CAST_TO_RAW('12345678901234567890123456789012');
    v_encrypted_data RAW(2000):=valor;
    v_descryted_data RAW(2000);
    v_descryted_string Varchar2(100);
begin
    v_descryted_data:=DBMS_CRYPTO.DECRYPT(src=>v_encrypted_data ,typ=>DBMS_CRYPTO.ENCRYPT_AES256+ DBMS_CRYPTO.CHAIN_CBC+DBMS_CRYPTO.PAD_PKCS5,key=>v_key);
    v_descryted_string:=UTL_RAW.CAST_TO_VARCHAR2(v_descryted_data);                                                                    
    return v_descryted_string;                                                                  
end;*/
--------------------------------------------------------
--  DDL for Function ENCRIPT
--------------------------------------------------------
/*CREATE OR REPLACE FUNCTION ENCRIPT (valor in varchar2) RETURN VARCHAR2 AS
    p_clave VARCHAR2(32) := '12345678901234567890123456789012';
    l_key RAW(32);
    l_data RAW(100);
    l_encrypted RAW(2000);
    l_encrypted_hex VARCHAR2(4000); -- Hexadecimal representation of the encrypted data
BEGIN
    l_key := UTL_RAW.CAST_TO_RAW(p_clave);
    l_data := UTL_RAW.CAST_TO_RAW(TO_CHAR(valor));
    l_encrypted := DBMS_CRYPTO.ENCRYPT(
        src => l_data,
        typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
        key => l_key
    );
    l_encrypted_hex := RAWTOHEX(l_encrypted);
    RETURN l_encrypted_hex;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error en la encriptacion: ' || SQLERRM);
END;*/
----------------------------------------------------------------------------------------------------------------------------------------------------------------------



    
    